### ISSUE TITLE
In the same room but don't see the other users?

### ISSUE THREAD

**Issue by tmhglnd** [munshkr/flok#149]
Hi! 

Lately I often run into the issue where I'm trying to enter the same room with someone else, but we don't see each other even tho we are still using the same url. Funny thing is that if the other person executes some Hydra code I do see the visuals on my screen, but the texteditor remains empty. We tried some things like disabling firewall/vpn and using the same browser to make sure nothing is intervening, but still this happens now and then. Do you have any idea what could be the issue?

**Comment by munshkr** [comment]
Hi Timo, can you tell me more about the network? Were you in the same local network, or via internet? Where were you and your friend connected to? Was it on flok.clic.cf?

Sounds like the WebRTC sync wasn't working correctly. It should've fallback down to qebsockets though, so that's a bug. Code evaluations work because those go through Websockets, not WebRTC.

**Comment by tmhglnd** [comment]
In the cases where this happened I was using flok.clic.cf indeed. Will check running a local version of flok if the same thing happens or not. When I was using flok.clic.cf it happend both when I was remotely connecting with my friend from a distance (so different wifi networks), but it has also happened once when we were in the same room using the same network.

**Comment by munshkr** [comment]
I had a typo on the TURN/STUN server configuration in my flok.clic.cf VPS, hopefully this is fixed now, but feel free to reopen if it keeps happening.

**Comment by tmhglnd** [comment]
Okay cool, let's see! 

A little while ago we still encountered the issue, but it also seemed it may have something to do with using Chrome Canary. When we switched to standard Chrome or Brave we did see eachother again.

**Comment by tmhglnd** [comment]
Hey munshkr! I'm sorry to re-open this but me and Saskia keep running into this issue. And we just tested with another friend over the network and they also don't see us or the code. But if one of us executes Hydra code we do see the visuals. For this we used `flok.cc`, and 2 of us are on the same wifi network, one was remote. We're having a hard time pinning it down. Trying different browsers, trying incognito windows, disabling VPN/Firewalls, but nothing really seems to make a difference. Did you have any other reports of this issue?
